[win] Specify UTF-8 charset explicitly for targets with wide strings
On Windows systems with non-English locales, the wide strings may cause
"Error C2001: Newline in constant".

2 solutions:
    Save the file with UTF-8 with BOM (byte-order mark).
    Specify UTF-8 charset for compilation. Used by this commit.

See discussions here:
    https://github.com/libusb/libusb/issues/207#issuecomment-288664124